/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.milaifontanals.wikiloc.vista;

import java.io.File;
import javax.swing.ImageIcon;
import org.milaifontanals.wikiloc.components.TextPrompt;

/**
 *
 * @author JUDIT
 */
public class panellAfegir_ruta extends javax.swing.JPanel {
   
    ImageIcon estrellaBlanca = new ImageIcon("img"+File.separator+"estrella_blanca.png");
    ImageIcon estrellaGroga = new ImageIcon("img"+File.separator+"estrella_groga.png");
    
    public panellAfegir_ruta() {
        initComponents();
        //TextPrompt placeHolder_titol = new TextPrompt("títol de la ruta",jTextField_titolRuta);
                
        for(int i = 1; i <= 24; i++ ){            
            jComboBox_tempsHruta.addItem(i+"");
        }
        
        for(int i = 1; i <= 60; i++ ){            
            jComboBox_tempsMruta.addItem(i+"");
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_titolRuta = new javax.swing.JTextField();
        jTextField_descRuta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_desnPruta = new javax.swing.JTextField();
        jTextField_desnNruta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_estrella1 = new javax.swing.JLabel();
        jLabel_estrella2 = new javax.swing.JLabel();
        jLabel_estrella3 = new javax.swing.JLabel();
        jLabel_estrella4 = new javax.swing.JLabel();
        jLabel_estrella5 = new javax.swing.JLabel();
        jComboBox_tempsHruta = new javax.swing.JComboBox<>();
        jComboBox_tempsMruta = new javax.swing.JComboBox<>();

        jTextField_titolRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_titolRutaActionPerformed(evt);
            }
        });

        jLabel1.setText("hores");

        jLabel2.setText("minuts");

        jLabel3.setText("dificultat 5 estrelles: ");

        jLabel4.setText("titol");

        jLabel5.setText("desc");

        jLabel6.setText("temps");

        jLabel7.setText("desnP");

        jLabel8.setText("desnN");

        jLabel9.setText("cercar llibreria format html??????");

        jLabel_estrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/wikiloc/components/estrella_groga.png"))); // NOI18N
        jLabel_estrella1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_estrella1MouseClicked(evt);
            }
        });

        jLabel_estrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/wikiloc/components/estrella_blanca.png"))); // NOI18N
        jLabel_estrella2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_estrella2MouseClicked(evt);
            }
        });

        jLabel_estrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/wikiloc/components/estrella_blanca.png"))); // NOI18N
        jLabel_estrella3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_estrella3MouseClicked(evt);
            }
        });

        jLabel_estrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/wikiloc/components/estrella_blanca.png"))); // NOI18N
        jLabel_estrella4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_estrella4MouseClicked(evt);
            }
        });

        jLabel_estrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/milaifontanals/wikiloc/components/estrella_blanca.png"))); // NOI18N
        jLabel_estrella5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_estrella5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_descRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jTextField_titolRuta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_tempsHruta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_desnNruta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                    .addComponent(jTextField_desnPruta, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox_tempsMruta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(364, 364, 364))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_estrella1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_estrella2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_estrella3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_estrella4)
                .addGap(18, 18, 18)
                .addComponent(jLabel_estrella5)
                .addGap(341, 341, 341))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_titolRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_descRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_tempsHruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_tempsMruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_desnPruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_desnNruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addComponent(jLabel_estrella1)
                    .addComponent(jLabel_estrella4)
                    .addComponent(jLabel_estrella3)
                    .addComponent(jLabel_estrella2)
                    .addComponent(jLabel_estrella5))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_titolRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_titolRutaActionPerformed
        
        
        
    }//GEN-LAST:event_jTextField_titolRutaActionPerformed

    private void jLabel_estrella1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_estrella1MouseClicked
        
        jLabel_estrella1.setIcon(estrellaGroga);
        jLabel_estrella2.setIcon(estrellaBlanca);
        jLabel_estrella3.setIcon(estrellaBlanca);
        jLabel_estrella4.setIcon(estrellaBlanca);
        jLabel_estrella5.setIcon(estrellaBlanca);
        
    }//GEN-LAST:event_jLabel_estrella1MouseClicked

    private void jLabel_estrella2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_estrella2MouseClicked
        
        jLabel_estrella1.setIcon(estrellaGroga);
        jLabel_estrella2.setIcon(estrellaGroga);
        jLabel_estrella3.setIcon(estrellaBlanca);
        jLabel_estrella4.setIcon(estrellaBlanca);
        jLabel_estrella5.setIcon(estrellaBlanca);
        
    }//GEN-LAST:event_jLabel_estrella2MouseClicked

    private void jLabel_estrella3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_estrella3MouseClicked
        
        jLabel_estrella1.setIcon(estrellaGroga);
        jLabel_estrella2.setIcon(estrellaGroga);
        jLabel_estrella3.setIcon(estrellaGroga);
        jLabel_estrella4.setIcon(estrellaBlanca);
        jLabel_estrella5.setIcon(estrellaBlanca);
        
    }//GEN-LAST:event_jLabel_estrella3MouseClicked

    private void jLabel_estrella4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_estrella4MouseClicked
        
        jLabel_estrella1.setIcon(estrellaGroga);
        jLabel_estrella2.setIcon(estrellaGroga);
        jLabel_estrella3.setIcon(estrellaGroga);
        jLabel_estrella4.setIcon(estrellaGroga);
        jLabel_estrella5.setIcon(estrellaBlanca);
        
    }//GEN-LAST:event_jLabel_estrella4MouseClicked

    private void jLabel_estrella5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_estrella5MouseClicked
        
        jLabel_estrella1.setIcon(estrellaGroga);
        jLabel_estrella2.setIcon(estrellaGroga);
        jLabel_estrella3.setIcon(estrellaGroga);
        jLabel_estrella4.setIcon(estrellaGroga);
        jLabel_estrella5.setIcon(estrellaGroga);


    }//GEN-LAST:event_jLabel_estrella5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_tempsHruta;
    private javax.swing.JComboBox<String> jComboBox_tempsMruta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_estrella1;
    private javax.swing.JLabel jLabel_estrella2;
    private javax.swing.JLabel jLabel_estrella3;
    private javax.swing.JLabel jLabel_estrella4;
    private javax.swing.JLabel jLabel_estrella5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_descRuta;
    private javax.swing.JTextField jTextField_desnNruta;
    private javax.swing.JTextField jTextField_desnPruta;
    private javax.swing.JTextField jTextField_titolRuta;
    // End of variables declaration//GEN-END:variables
}
